### ISSUE TITLE
Please add a demonstration video on Asciinema for how to use it.

### ISSUE THREAD

**Issue by luisadha** [agung2001/KATA-Ep6#1]
Please add a demonstration video on Asciineman for how to use it.

**Comment by agung2001** [comment]
hi @luisadha thx for the feedback

I've added the YouTube video URL that demonstrates this project
you can find it in this readme file: https://github.com/agung2001/KATA-Ep6/blob/9997f029641bf0f353dade50605e3166dc315118/README.md

I'll close this issue now 👍
